import { NextAuthProvider } from "./providers";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NextTopLoader
          color="#06b6d4" // Sesuai dengan warna cyan-500 di tema Anda
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false} // YouTube biasanya tidak menampilkan spinner
          easing="ease"
          speed={200}
          shadow="0 0 10px #06b6d4,0 0 5px #06b6d4"
        />
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
